- name: Actualizacion del sistema operativo y configurado
  host: all
  become: yes
  become_method: sudo
  remote_user: vagrant
  task:
    import_task: ansible/ejercicio1/main.yml
    # import_task: ansible/ejercicio2/main.yml
    # import_task: ansible/ejercicio3/main.yml
    # import_task: ansible/ejercicio4/main.yml
    # import_task: ansible/ejercicio5/main.yml
    # import_task: ansible/ejercicio6/main.yml
    # import_task: ansible/ejercicio7/main.yml
    # import_task: ansible/ejercicio8/main.yml
    # import_task: ansible/ejercicio9/main.yml
    # import_task: ansible/ejercicio10/main.yml
    