########### Pregunta 2 ###########
- name: Reiniciar Nginx # para aplicar los nuevos cambios al servidor
  service:
    name: nginx
    state: restarted

- name: Reiniciar UFW # para aplicar los nuevos cambios al firewall
  command: ufw reload

########### Pregunta 3 ###########
- name: Recargar systemd
  command: systemctl daemon-reload

- name: Reiniciar Flask app
  systemd:
    name: flask_app_{{ item }}
    state: restarted
  with_items:
    - 5000
    - 5001
    - 5002

########### Pregunta 4 ###########
- name: Reiniciar Prometheus
  systemd:
    name: prometheus
    state: restarted


########### Pregunta 5 ###########
- name: Reiniciar PostgreSQL
  service:
    name: postgresql
    state: restarted

- name: Reiniciar Keepalived
  service:
    name: keepalived
    state: restarted

########### Pregunta 6 ###########
- name: Reiniciar SSH
  service:
    name: sshd
    state: restarted

- name: Reiniciar Fail2ban
  service:
    name: fail2ban
    state: restarted

- name: Reiniciar PAM
  command: pam-auth-update --force

- name: Reiniciar AppArmor
  service:
    name: apparmor
    state: restarted