- name: Recargar systemd
  command: systemctl daemon-reload

- name: Reiniciar Flask app
  systemd:
    name: flask_app_{{ item }}
    state: restarted
  with_items:
    - 5000
    - 5001
    - 5002

- name: Reiniciar Nginx
  service:
    name: nginx
    state: restarted

- name: Reiniciar UFW
  command: ufw reload