########### Pregunta 2 ###########
- name: Reiniciar Nginx # para aplicar los nuevos cambios al servidor
  service:
    name: nginx
    state: restarted

- name: Reiniciar UFW # para aplicar los nuevos cambios al firewall
  command: ufw reload

########### Pregunta 3 ###########
- name: Recargar systemd
  command: systemctl daemon-reload

- name: Reiniciar Flask app
  systemd:
    name: flask_app_{{ item }}
    state: restarted
  with_items:
    - 5000
    - 5001
    - 5002

########### Pregunta 4 ###########
- name: Reiniciar Prometheus
  systemd:
    name: prometheus
    state: restarted


########### Pregunta 5 ###########
- name: Reiniciar PostgreSQL
  service:
    name: postgresql
    state: restarted

- name: Reiniciar Keepalived
  service:
    name: keepalived
    state: restarted

########### Pregunta 6 ###########
- name: Reiniciar SSH
  service:
    name: sshd
    state: restarted

- name: Reiniciar Fail2ban
  service:
    name: fail2ban
    state: restarted

- name: Reiniciar PAM
  command: pam-auth-update --force

- name: Reiniciar AppArmor
  service:
    name: apparmor
    state: restarted

########### Pregunta 8 ###########

- name: Reiniciar Docker
  service:
    name: docker
    state: restarted

- name: Recargar Nginx
  service:
    name: nginx
    state: reloaded

########### Pregunta 9 ###########
- name: Reiniciar Docker Compose
  command: docker-compose restart
  args:
    chdir: /opt/docker_compose_app

########### Pregunta 10 ###########
- name: Notificar resultados de CI
  debug:
    msg: "Pipeline de CI completado exitosamente"
  when: test_results is defined and test_results.rc == 0