---
- name: Instalar Nginx
  apt:
    name: nginx
    state: present

- name: Generar certificados SSL autofirmados
  command: openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -subj "/C=US/ST=State/L=City/O=Organization/OU=Department/CN=localhost" -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt

- name: Crear archivo de parámetros Diffie-Hellman
  command: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048

- name: Configurar Nginx para utilizar SSL
  template:
    src: templates/nginx_ssl.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: Reiniciar Nginx

- name: Habilitar y configurar el firewall UFW
  ufw:
    rule: allow
    name: "{{ item }}"
  with_items:
    - 'OpenSSH'
    - 'Nginx Full'
  notify: Reiniciar UFW